name: ci

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    Tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.22'

            - name: Test
              run: go test -v ./...

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Build
              run: go build -v ./...
