name: ci

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    style:
        name: Style
        runs-on: ubuntu-latest
      
        steps:
            - name: Check out code
              uses: actions/checkout@v4
        
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23.0"
            
            - name: Styling codebase
              run: test -z $(go fmt ./...)
          
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.22'

            - name: Test
              run: go test -cover ./...

    build:
        name: Build
        runs-on: ubuntu-latest
      
        steps:
            - name: Check out code
              uses: actions/checkout@v4
        
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23.0"
      
            - name: Build
              run: go build -v ./...
